loki:
  commonConfig:
    replication_factor: 3
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: 's3'
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: foo.aws.com
      region: <AWS region>
      secretAccessKey: supersecret
      accessKeyId: secret
      s3ForcePathStyle: false
      insecure: false
singleBinary:
  replicas: 3
