apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.selectorLabels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          {{- if or (and .Values.salam (default false .Values.salam.enabled)) (and .Values.khodafez (default false .Values.khodafez.enabled)) }}
            env:
              {{- if and .Values.salam (default false .Values.salam.enabled) }}
              - name: SALAM_MESSAGES
                value: {{ .Values.salam.messages | toJson | quote }}
              {{- end }}
              {{- if and .Values.khodafez (default false .Values.khodafez.enabled) }}
              - name: KHODAFEZ_VARIANTS
                value: {{ .Values.khodafez.variants | toJson | quote }}
              {{- end }}
          {{- end }}
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "nginx.fullname" . }}-config
