#log collector or monitoring agent—making sure that exactly one pod runs per node
# kubectl get ds

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: fluentd
spec:
  selector: #important
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
      name: fluentd
    spec:
      tolerations: #important, effect tells Kubernetes not to schedule any pods that do not tolerate this taint.
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: gcr.io/google_containers/fluentd-elasticsearch:1.3
        env:
         - name: FLUENTD_ARGS
           value: -qq
        volumeMounts: #important
         - name: varlog
           mountPath: /varlog
         - name: containers
           mountPath: /var/lib/docker/containers
      volumes:
         - hostPath:
             path: /var/log
           name: varlog
         - hostPath:
             path: /var/lib/docker/containers
           name: containers