apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
